In [142]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from scikeras.wrappers import KerasClassifier

In [143]:
# load dataset
dataset = np.loadtxt("https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv", delimiter=",")

In [144]:
# split into input (X) and output (Y) variables
X = dataset[:,0:8]
Y = dataset[:,8]

In [147]:
# Function to create model, required for KerasClassifier
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(12, input_shape=(8,), activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [148]:
# fix random seed for reproducibility
seed = 7
tf.random.set_seed(seed)

In [149]:
# create model
model = KerasClassifier(model=create_model, verbose=0)

In [ ]:
# define the grid search parameters
batch_size = [10, 20, 40, 60, 80, 100]
epochs = [10, 50, 100]
param_grid = dict(batch_size=batch_size, epochs=epochs)
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)
grid_result = grid.fit(X, Y)

In [ ]:
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

In [19]:
x_train = tf.random.normal((10,1), 1, 1, dtype=tf.float32)
print(x_train)

tf.Tensor(
[[ 2.359313 ]
 [ 0.1013025]
 [ 1.938796 ]
 [-0.4313997]
 [ 1.3619559]
 [-0.4581666]
 [ 1.0051461]
 [ 1.190316 ]
 [ 1.5289392]
 [ 1.007003 ]], shape=(10, 1), dtype=float32)


In [140]:
tf.random.set_seed(3)
first = tf.random.normal((10,1), 1, 1)
first

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 0.17036277],
       [-0.82662714],
       [ 1.1251936 ],
       [ 2.1770082 ],
       [-0.1696676 ],
       [ 0.9906755 ],
       [ 2.7336211 ],
       [-0.03432238],
       [ 1.1381068 ],
       [ 0.08535814]], dtype=float32)>

In [104]:
tf.random.set_seed(3)
first = tf.random.normal((10,1), 1, 1, dtype=tf.float32)
print(first)
sec = tf.random.normal((10,1), 1, 1, dtype=tf.float32)
print(sec)

tf.Tensor(
[[ 0.17036277]
 [-0.82662714]
 [ 1.1251936 ]
 [ 2.1770082 ]
 [-0.1696676 ]
 [ 0.9906755 ]
 [ 2.7336211 ]
 [-0.03432238]
 [ 1.1381068 ]
 [ 0.08535814]], shape=(10, 1), dtype=float32)
tf.Tensor(
[[ 2.6663146 ]
 [ 1.7051975 ]
 [ 2.8652127 ]
 [ 1.834109  ]
 [-0.02303874]
 [ 1.2670431 ]
 [ 1.5003455 ]
 [ 1.0385396 ]
 [ 2.3715906 ]
 [-0.27997875]], shape=(10, 1), dtype=float32)
