# Sample codes with Numpy

This a collection of numpy codes performing linear algebraic equations.
I know how to solve this manually (How to get  the output behind the codes) but Im not doing that in this notebook, If required I'm glady make one.

In [2]:
import numpy as np

### Magnetude/lenght of a vector

In [18]:
v = np.array([-12,8,2])
v_norm = np.linalg.norm(v)
v_norm

14.560219778561036

### Transpose of a square matrix, Columns into rows.

In [11]:
A = np.array([[0,2,1],[-1,-2,0],[-1,1,2]])
print(A)
print('\n')
print(A.T)

[[ 0  2  1]
 [-1 -2  0]
 [-1  1  2]]


[[ 0 -1 -1]
 [ 2 -2  1]
 [ 1  0  2]]


### Inverse of matrix A

In [13]:
np.linalg.inv(A)

array([[-4., -3.,  2.],
       [ 2.,  1., -1.],
       [-3., -2.,  2.]])

### Solve for unknown variables in a system on linear equations in Ax=b form

Find the value of x,y,z

x + 4y -  z = -1	
-x - 3y + 2z =  2	
2x -  y - 2z = -2	


In [22]:
# convert to Ax=b form.

# each array in A is an equation from the above system of equations
A = np.array([[1,4,-1],[-1,-3,2],[2,-1,-2]])

# the solution to each equation
b = np.array([-1,2,-2])

# solve for x, y, and z
x,y,z = np.linalg.solve(A,b)
x,y,z

(0.0, 0.0, 1.0)

###  Find the angle in degress

In [4]:
c = np.array([3,-1,2])
d = np.array([0,-1,1])

dot = np.dot(c,d)
c_norm = np.linalg.norm(c)
d_norm = np.linalg.norm(d)

cd_norm = c_norm * d_norm

angle = dot / cd_norm
angle

0.5669467095138409

### Multiplicatio/Subration of Matrices

In [6]:
a = np.array([[2,3],[-2,0]])
b = np.array([[1,-2],[3,1]])

out = 4 * a - b
out

array([[  7,  14],
       [-11,  -1]])

### Find Shape
 - usage of @ and dot
 - @   -> multiply matrices
 - dot -> multiply with vector

In [9]:
# This Matrices
a = np.array([[2,3,4],[-2,-2,-2],[0,1,0],[-1,-3,-2]])
b = np.array([[-1,-2,-1],[2,1,-2],[3,0,-3]])

# This is a Vector
c = np.array([1,2,3])

ab = a @ b
abc = np.dot(ab,c)

abc.shape

(4,)

### Create 4x4 identity matrix

In [16]:
identity = np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Combine these three arrays into a 4x3 matrix

In [24]:
vector_1=np.array([-2,-6,2,3])
vector_2=np.array([4,1,-3,8])
vector_3=np.array([5,-7,9,0])

matrix=np.column_stack([vector_1,vector_2,vector_3])
matrix

array([[-2,  4,  5],
       [-6,  1, -7],
       [ 2, -3,  9],
       [ 3,  8,  0]])

### 5-element vector of zeros


In [28]:
zero5_vector = np.zeros(5)
zero5_vector

array([0., 0., 0., 0., 0.])

### 3x2 matrix of zeros

In [30]:
zero32_vector = np.zeros((3,2))
zero32_vector

array([[0., 0.],
       [0., 0.],
       [0., 0.]])